name: Deploy to prod
on:
  push:
    branches: [ "main" ]


jobs:
  test: # Название джобы
    runs-on: ubuntu-latest   # Где должна выполняться джоба.
    # Здесь укажем GitHub-hosted runner - среду выполнения, которую предоставляет сам GitHub.
    steps: # Перечень шагов, которые необходимо выполнить в рамках джобы.
      - uses: actions/checkout@v3
      - uses: spring-io/spring-gradle-build-action@v2
      - name: Run tests
        run: ./gradlew test

  debug:
    runs-on: self-hosted # Запускаем на раннере, который настроили до этого.
    needs: test
    steps:
      - run: echo MINI DEBUG START
      - run: pwd
      - run: ls
      - run: echo $USER
      - run: ls -l
      - run: echo MINI DEBUG END


  build_docker:
    runs-on: self-hosted # Запускаем на раннере, который настроили до этого.
    needs: test
    steps:
      - name: checkout repo
        uses: actions/checkout@v3

      - name: Build
        run: ./gradlew bootJar

      - name: Docker build
        run: docker build -t fclaybackend:latest .


  deploy_container:
    runs-on: self-hosted
    needs: build_docker
    steps:
      - name: stop current container
        run: docker stop fclaybackend-container
        continue-on-error: true

      - name: remove current container
        run: docker rm fclaybackend-container
        continue-on-error: true

      - name: start new container
        run: docker run --name=fclaybackend-container -v fclaybackend-data:/var/lib/fclaybackend -p 8080:8080 -d fclaybackend:latest

